### ISSUE TITLE
Review DAG: pull_survey_cto_data.py

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/connectors#10]
We would like to review and refactor the code for the following dag: https://github.com/hikaya-io/connectors/blob/master/DAGs/pull_survey_cto_data.py

- Review DAGs
- Refactor the DAG
- Suggest any changes to optimize the DAG

**Comment by amosnjoroge** [comment]
@JumaKahiga Please refer to the [surveycto-python library](https://github.com/IDinsight/surveycto-python) on how to use the SurveyCTO API.
