### ISSUE TITLE
Review DAGs: export_newdea_db.py

### ISSUE THREAD

**Issue by andrewtpham** [hikaya-io/connectors#9]
We would like to review and refactor the code for the following dag: https://github.com/hikaya-io/connectors/blob/master/DAGs/export_newdea_db.py

- Review DAGs
- Refactor the DAG
- Suggest any changes to optimize the DAG

**Comment by andrewtpham** [comment]
@sannleen to identify the Airflow version that is currently deployed so that it can be set up locally when running the DAG.

**Comment by amosnjoroge** [comment]
@michaelbukachi our current version is 1.10.4
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/16039248/105386568-9ba8ac00-5c25-11eb-803b-4a092d26219e.png">
